apiVersion: v1
kind: Pod
metadata: 
  name: pod-dema-ca
  namespace: default
  labels: 
    app: myapp
    tier: frontend
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    ports:
    - name: http
      containerPort: 80
  serviceAccountName: admin


