apiVersion: v1
kind: Pod
metadata: 
  name: pod-cm-1
  namespace: default
  labels: 
    app: myapp
    tier: frontend
  annotations:
    cdy.com/create-by: cluster  admin"
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    ports:
    - name: http
      containerPort: 80
    - name: https
      containerPort: 443 
    env:
    - name: NGXIN_SERVER_PORT
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: nginx.port
    - name: NGINX_SERVER_NAME
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: server_name

